#Day 01 in Day 02
#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)

In [2]:

import numpy as np

In [3]:
import math
math.sqrt(16)

4.0

In [4]:
l1=[21,12,'hello world']
print(l1)
type(l1)

[21, 12, 'hello world']


list

#THE BASICS :

#initialize array

# with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage;

In [5]:

a=np.array([1,2,3],dtype="int16")  
print("one dimensional array :",a)

b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

one dimensional array : [1 2 3]
two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


#Get Dimension

In [ ]:

print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)

dimension of a : 1
dimension of b : 2


#Get Shape

#its a vector so its tellings us one dimension 

In [ ]:

print("shape of a :",a.shape) 
print("shape of b :",b.shape)


shape of a : (3,)
shape of b : (2, 4)


#Get  Type

In [ ]:

print("a type is :",a.dtype)

a type is : int16


#Get Size

In [ ]:

print("size of a :",a.size) # # of element in the array.i,e length of array;


size of a : 3


#total size
# size of single element in the array .i,e in bytes;

In [ ]:

print("a item size :",a.itemsize) 
print("total size is a:",a.size*a.itemsize)


a item size : 2
total size is a: 6


#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

#Get specific element [row,column] -ve index is possible similar to list;

In [ ]:

b[1,2]


np.float64(4.2)

#Get specific row [row,:]#we use slicing(:) operation


In [ ]:
print("row :",b[1,0:1]);


row : [2.1]


#Get specific column[:,column]


In [ ]:
print("column :",b[:,1])

column : [2. 3.]


#Getting a little more fancy [starindex:endindex:steps]


In [ ]:
print("subset of specific row",b[1,1::2])


subset of specific row [3.  4.5]


#change element

In [ ]:

b[1,2]=8
print(b)

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


In [ ]:
b[:,2]=[9,4]
b

array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [6]:
int(1.3)

1

# 3-d Array Example :

In [20]:
c=np.array([[
    [1,2,8],[3,4,7]
    ],
    [
        [4,5,5],[6,8,9]
        ]
])
c

array([[[1, 2, 8],
        [3, 4, 7]],

       [[4, 5, 5],
        [6, 8, 9]]])

In [21]:
type(c)

numpy.ndarray

In [23]:
c.ndim

3

In [24]:
c.size

12

In [25]:
c.itemsize

8

In [26]:
c.shape

(2, 2, 3)

total memory taken

In [27]:
c.size*c.itemsize

96

In [29]:
c

array([[[1, 2, 8],
        [3, 4, 7]],

       [[4, 5, 5],
        [6, 8, 9]]])

In [30]:
# get the specificelement (work outside in)
print("specific element is from first list 1st row 2nd col and :",c[0,0,1 ])

specific element is from first list 1st row 2nd col and : 2


In [31]:
print("element from 2nd list 2nd row 3rd col:",c[1,1,2])

element from 2nd list 2nd row 3rd col: 9


In [33]:
print(c[1,1,1])

8


#### Initializing different types of array
default type of any matrix is float and if we using full method then the data type is int

In [7]:
A=np.zeros((2,3),dtype=int  )#2 ROW AND 3 COLUMNS

In [8]:
A

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
A.ndim

2

In [10]:
A.shape

(2, 3)

In [11]:
A.size

6

1's matrix

In [15]:
a=np.ones((3,4),dtype="int16")
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [16]:
a.shape

(3, 4)

In [18]:
a[1,1]=22
a

array([[ 1,  1,  1,  1],
       [ 1, 22,  1,  1],
       [ 1,  1,  1,  1]], dtype=int16)

In [23]:
# any other number 
z=np.full(a.shape,95.7,dtype="float")

#### reuse the already existing array one value to another

In [24]:
np.full_like(z,200,dtype="float")

array([[200., 200., 200., 200.],
       [200., 200., 200., 200.],
       [200., 200., 200., 200.]])

Random matrix

In [25]:
np.random.random_sample((2,3))

array([[0.69575478, 0.62098594, 0.91657106],
       [0.05347421, 0.19393977, 0.33057283]])

In [30]:
e=np.random.rand(2,4)
e

array([[0.91014269, 0.8023555 , 0.20421947, 0.68597524],
       [0.75383052, 0.81240148, 0.86889919, 0.79493443]])

In [28]:
np.random.randint(2,4,e.shape)

array([[3, 3, 3, 3],
       [3, 3, 2, 2]], dtype=int32)

In [29]:
np.random.randint(2,4,size=(3,3))

array([[3, 3, 3],
       [2, 2, 2],
       [2, 3, 3]], dtype=int32)

In [ ]:
# Generate identity only one argument bcz identity matrix is a square matrix
np.identity(2)#rows and colums are same 2,2

array([[1., 0.],
       [0., 1.]])